### ISSUE TITLE
[demo] Layout using layout-grid

### ISSUE THREAD

**Issue by hardtack** [Hardtack/react-mdcw#16]
When we write demo, there were no layout components like layout-grid component.
Now, we have nice layout component, refactor it!

**Comment by dhruvdutt** [comment]
Where exactly do we need to refactor? Which demos?

**Comment by hardtack** [comment]
@dhruvdutt 

Oh I forgot to close it.

The demo page's layout was too naive to maintain when I opened this issue. But now I've refactor that now.

Thank you for reminding

**Comment by dhruvdutt** [comment]
Welcome! Nice job btw. I love reading your code. :sunglasses:
