### ISSUE TITLE
[toolbar] new component

### ISSUE THREAD

**Issue by hardtack** [Hardtack/react-mdcw#19]
Implement [MDCToolbar](https://github.com/material-components/material-components-web/tree/master/packages/mdc-toolbar) component

**Comment by hardtack** [comment]
Done in [feature/add-toolbar](https://github.com/Hardtack/react-material-components-web/tree/feature/add-toolbar) branch.

But google not published this component yet. 
So hold on...

**Comment by gutenye** [comment]
@Hardtack Google has published Toolbar component, https://material.io/components/web/catalog/toolbar/
What's the current status of this now?

**Comment by gutenye** [comment]
@Hardtack I found toolbar is already implemented: https://github.com/react-mdc/react-material-components-web/tree/develop/packages/toolbar
Is it only missing documentation?

**Comment by hardtack** [comment]
@gutenye Yes, some components' documentations are missing and we should add for them.
