### ISSUE TITLE
[common] TypeScript

### ISSUE THREAD

**Issue by hardtack** [Hardtack/react-mdcw#22]
I'm using react-material-components-web for my private project. And that project seems gonna use TypeScript instead of ECMA6 + Flow.
So I'm considering to support TypeScript for react-material-components-web

Supporting TypeScript will be cool feature.

We have two options to do this

1. Migrate to TypeScript and write `.flow` file manually or use [flowgen](https://github.com/joarwilk/flowgen)

  - Pros

    * We can you TypeScript's mature tools

    * ~Can be easily used by my private project~

  - Cons

    * Should migrate all codes

    * Have to learn new language

2. Just write `.d.ts` files

  - Pros

    * Don't have to migrate our codes

  - Cons

    * Should keep fight with immatureness of flow

**Comment by hardtack** [comment]
Ref. https://github.com/material-components/material-components-web/issues/134

**Comment by maxcan** [comment]
Strong vote here in favor of typescript support.  If you're willing, i think migrating to TS is the most sustainable, value adding approach

**Comment by hardtack** [comment]
@maxcan 
I'm doing some research for TypeScript.
Maybe It will be migrated to TypeScript if there's no critical problem.

**Comment by hardtack** [comment]
flowgen is not capable with our project.
I'll consider flow support later

**Comment by hardtack** [comment]
Closed by #24
