### ISSUE TITLE
[textfield] Support password input

### ISSUE THREAD

**Issue by ukstv** [Hardtack/react-mdcw#46]
Now Textfield uses <Input type="text">. It could be useful to specify additional property that switches that to password input.

**Comment by Ephemera** [comment]
`<Textfield.Input type="password">`
Isn't it enough?

**Comment by hardtack** [comment]
@ukstv @Ephemera 
Right, You can make a password like following
``` Typescript
<Textfield>
    <Textfield.Input type="password" />
</Textfield>
```

But, password field might be used usually. So I'll consider to make better simpler API to create password field. Thanks!
